### ISSUE TITLE
Suggestion - Snippets => CASE

### ISSUE THREAD

**Issue by ghost** [Gunders89/language-scl#2]
Hi there.

_Sorry for not forking your project and making changes for you to absorb later. [blush] I do not know how to yet / have not tried yet._

I hope to show you something:
**./snippets/language-scl.cson**
```coffee
'.source.scl':
  # other code excluded
  'Case statement':
    'prefix': 'case'
    'body': """// CASE STATMENT
    case ${1:#numberTag} of
      ${2:0}: // First step
        ;
      ${3:1}: // Last step
        ;
      else
        ${1:#numberTag} := 0; //..restart
      end_case;"""
```
Note how the ` """ ` is used - no need for `\n` or `\t`. The "origin line" is inline with the `'` of `'body'`. The tabs are now replaced by spaces. Two spaces for each tab.

Note also the place-holder entries like ${1:**#numberTag**} (also `0` and `1`). After placing the CASE you can cycle through the place-holders pressing <kbd>Tab</kbd>. When filling in **#numberTag**, both instances will be changed.

Helpful?
Best regards.
\- Dan Padric

**Comment by Gunders89** [comment]
Hi.
Yes I'm awear of the numbering and that you can cycle through it (it is being used in the other snippets). I just thought that I'd try to omit the explanatory text or any suggestions for the case-snippet, and see how that feels for a while.  You can still cycle through the correct positions, even though the placeholders are not there.
However, I see your point in defaulting with ${2:0} through ${2:n} for the cases. It just so happens that we mostly use constants as cases where I work. 

Regarding \n \t and the """:
This is a personal preference. Old habits die hard, and so I'm used to reading \n \t for string operations. I feel more in control, if you know what I mean.

**Comment by Gunders89** [comment]
I can't decide if I like that the snippet produces semi-colons for each case. Like so:
```
case siInt of 
  0: 
    ;
  1:
    ;  
end_case;
```
I know TIA does this, but I tend to write them anyway (it's in my hands). So I often end up with having to delete one of them. You could argue that "at least it will compile if you forget to do something for a case", but when would that be a good thing? I mean, useless code is more of a nuisance than having to type the semi-colon.

**Comment by ghost** [comment]
Hi. Thanks for sharing your thoughts.

Much of what you mention boils down to personal choice. What I proposed is what **I** would do. (smile) I know SCL from TIA.

The `"""` makes it easier that you do not need to use the escape key when `// comment`. It also makes it easier for others to understand what goes on and follow the example to expand the snippets. 

Consider:
- did you publish this for only you or for others too?
- what do other people (not you and me only) want?

The `siInt` is clear that an INT is needed. That is okay.

Having an active place-holder in place feels like a 'must'. 
But having `0` or variable for example `FIRST` does not really matter.. a number is short and clean IMO.

As for the `;` - there it does need _**something**_, A reminder of indentation as well as "here is code needed". I like the `;` there, but for example `// code`  as marker is okay too. As far as I know `;` and `#` are put into place when you export. Would you please test this on Step7 V5.x (Classic) and let me know.

When it comes to the `#` - it would make it easier to identify and syntax colourize the variables. There are still much syntax colouring that can occur - if you want to. 

I am currently busy with STL.. still in alpha stage. I can send you a picture if you want to know how it looks like. I also have a rough idea on how to **TIA -> Classic** for STL code. I am currently doing it for an active project.

You do know that custom snippets can also be included in Atom's main keymap file? So even if we do not agree, (wink) I can go and create my own versions without changing your project. So I'll give opinions if you want them, but you go with what **you** think is good for **your** project. 

Your thoughts?
\- Dan

**Comment by Gunders89** [comment]
Variable names starting with `#` does not compile in Step 7 V5.x.

Highlighting variables seems kind of exsessive to me. I have yet to see that being used in other IDEs for a variaty of languages. However, identifying variables can of course be useful if you are going for a language parser.

**Comment by ghost** [comment]
`#` is handled in _STL_ code in Step7 V5.5.. 
though not in the variable declaration section
```STL
FUNCTION "Messages" : VOID
TITLE =Display fault messages on OP.

VAR_IN_OUT
  sms : INT ;	// Message number
END_VAR
BEGIN
NETWORK
TITLE =Default message.

      L     0; 
      T     #sms; 
      NOP   0; 
END_FUNCTION
```

I rather like having syntax colouring to distinguish global variables (`"`) vs local variables (`#`) vs numerical constants. THAT is however how _I_ like it - you do as you see fit.

\- Dan
