### ISSUE TITLE
Add IEC counters and timers as snippet content

### ISSUE THREAD

**Issue by erjac8912** [Gunders89/language-scl#5]
Hi!

I'm unfortunately not that familiar with working with the snippet editor so here's a wish for the future. I would like to have the following functions as snippets for multi instance use when working whit FB's. This makes the ATOM-editor more complete as a tool for SCL-coding. 

#TOF(IN:=_bool_in_,
     PT:=_time_in_,
     Q=>_bool_out_,
     ET=>_time_out_);

#TON(IN:=_bool_in_,
     PT:=_time_in_,
     Q=>_bool_out_,
     ET=>_time_out_);

#CTU(CU:=_bool_in_,
     R:=_bool_in_,
     PV:=_int_in_,
     Q=>_bool_out_,
     CV=>_int_out_);

#CTUD(CU:=_bool_in_,
      CD:=_bool_in_,
      R:=_bool_in_,
      LD:=_bool_in_,
      PV:=_int_in_,
      QU=>_bool_out_,
      QD=>_bool_out_,
      CV=>_int_out_);

#TP(IN:=_bool_in_,
    PT:=_time_in_,
    Q=>_bool_out_,
    ET=>_time_out_);

Thanks in advance.

**Comment by Gunders89** [comment]
Thanks for your feedback and suggestion. This has now been added. Update the package in Atom and reload the editor.
